<a href="https://colab.research.google.com/github/yeshwanthv5/colab-notebooks/blob/master/pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip3 install torch==1.2.0+cu92 torchvision==0.4.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html


Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 663.1MB 26kB/s 
     |████████████████████████████████| 8.8MB 44.8MB/s 
  Found existing installation: torch 1.3.1
    Uninstalling torch-1.3.1:
      Successfully uninstalled torch-1.3.1
  Found existing installation: torchvision 0.4.2
    Uninstalling torchvision-0.4.2:
      Successfully uninstalled torchvision-0.4.2


In [0]:
import torch

In [15]:
dtype = torch.FloatTensor

N, D_in, H, D_out = 2,2,5,2
x = torch.randn(N, D_in).type(dtype)
y = torch.randn(N, D_out).type(dtype)
w1 = torch.randn(D_in, H).type(dtype)
w2 = torch.randn(H, D_out).type(dtype)
print(w1)
print(w2)
learning_rate = 1e-6
for t in range(500):
  h = x.mm(w1)
  h_relu = h.clamp(min = 0)
  y_pred = h_relu.mm(w2)
  loss = (y_pred - y).pow(2).sum()

  grad_y_pred = 2.0 * (y_pred - y)
  grad_w2 = h_relu.t().mm(grad_y_pred)
  grad_h_relu = grad_y_pred.mm(w2.t())
  grad_h = grad_h_relu.clone()
  grad_h[h < 0] = 0
  grad_w1 = x.t().mm(grad_h)

  w1 -= learning_rate * grad_w1
  w2 -= learning_rate * grad_w2
print(w1)
print(w2)

tensor([[ 1.0964, -0.3667,  0.5090, -0.7071, -1.3930],
        [ 1.3946,  1.3612, -0.9434,  0.5065,  0.3078]])
tensor([[ 1.0175, -2.4038],
        [-0.0129,  0.2400],
        [-0.1312, -0.1137],
        [ 0.8243,  1.0567],
        [-0.1951,  0.0309]])
tensor([[ 1.0792, -0.3653,  0.5088, -0.7071, -1.3930],
        [ 1.3894,  1.3616, -0.9435,  0.5065,  0.3078]])
tensor([[ 1.0118, -2.3954],
        [-0.0130,  0.2403],
        [-0.1330, -0.1116],
        [ 0.8243,  1.0567],
        [-0.1951,  0.0309]])
